### PR TITLE
[TASK] Compatibility with "evoweb/extender" v10

### PR DESCRIPTION
**Pull request by Apen**

### CODE REVIEW

**Comment by Apen** [comment]
i cant sync the PR but i add the new declaration for "extender" in https://github.com/Apen/powermailautocomplete/commit/a6b288d610790abbb1d058c7b4a8b4bcbaafc2bf

**Comment by thomasrawiel** [comment]
evoweb/extender 10 breaks with an exception, might add this later

**Comment by Apen** [comment]
I tested it with the dev-develop version and my fork (https://github.com/Apen/powermailautocomplete/tree/patch-1).
Didnt test with 10 at the moment.

**Comment by thomasrawiel** [comment]
@Apen First, thanks for the pull requests. I added your code accordingly. Here's a hint for use with TYPO3 12 and evoweb/extender 10.1.0: Issue https://github.com/thomasrawiel/powermailautocomplete/issues/5

**Pull request closed without merging**
